// ============================================================
// The payment provider abstraction (§9)
// ------------------------------------------------------------
// §9 is explicit: DO NOT HARD-CODE A SINGLE PAYMENT GATEWAY. Nigerian hospitals
// change processors, and a system welded to one becomes a rewrite the day the
// contract does.
//
// So everything above this layer speaks in one vocabulary — initiate, verify,
// refund — and each adapter translates. The differences the adapters absorb are
// not cosmetic:
//
//   Paystack     amounts in KOBO      signature is HMAC-SHA512 over the raw body
//   Flutterwave  amounts in NAIRA     signature is a shared hash in a header
//
// That first row is why the abstraction earns its place. This application is
// kobo-native, so Paystack needs no conversion at all, while Flutterwave needs
// exactly one — performed here, in one place, rather than scattered through
// routes where a second conversion would eventually be added by mistake.
//
// WHAT NO ADAPTER MAY DO: decide that a payment succeeded. An adapter reports
// what the provider said. Whether that constitutes payment is decided by
// reconcileVerification() against the invoice, and then by the payment state
// machine. Keeping that judgement out of the adapters means adding a provider
// cannot weaken the rules.
// ============================================================

import { NormalisedEvent, ProviderCode, SignatureVerdict, verifyFlutterwaveSignature, verifyPaystackSignature } from './webhooks';

export interface InitiateRequest {
  /** OUR reference. Generated by us so a webhook can be matched to an invoice. */
  reference: string;
  /** Kobo. Always kobo at this boundary; adapters convert outward if they must. */
  amount: number;
  currency: string;
  email: string;
  /** Where the patient is sent after paying. */
  callbackUrl?: string;
  /** Carried through the provider and returned on the webhook. */
  metadata?: Record<string, unknown>;
}

export interface InitiateResult {
  /** Where to send the patient. */
  authorizationUrl: string;
  /** The provider's own handle for this attempt. */
  providerReference: string;
  raw: unknown;
}

export interface VerifyResult {
  /** Kobo, normalised. This is the figure the application believes. */
  amount: number;
  currency: string;
  /** 'success' | 'failed' | 'abandoned' | provider-specific. */
  status: string;
  providerTransactionId: string | null;
  paidAt: Date | null;
  raw: unknown;
}

export interface PaymentProviderAdapter {
  readonly code: ProviderCode | 'DESK';
  readonly supportsNativeSplit: boolean;

  /** Is this provider usable right now — are its credentials configured? */
  isConfigured(): boolean;

  /** Send the patient to pay. */
  initiate(request: InitiateRequest): Promise<InitiateResult>;

  /**
   * Ask the provider, server to server, what actually happened.
   *
   * This is the ONLY thing that may cause money to be credited. A webhook
   * triggers it; a webhook never replaces it.
   */
  verify(reference: string): Promise<VerifyResult>;

  /** Check a webhook signature against the raw body as received. */
  verifySignature(params: { rawBody: string; headers: Headers }): SignatureVerdict;

  /** Pull our fields out of a provider payload. */
  parseEvent(payload: unknown): NormalisedEvent;
}

export class ProviderError extends Error {
  code: string;
  httpStatus?: number;
  constructor(code: string, message: string, httpStatus?: number) {
    super(message);
    this.name = 'ProviderError';
    this.code = code;
    this.httpStatus = httpStatus;
  }
}

/**
 * One HTTP call to a provider.
 *
 * Times out. A gateway that has stopped answering must not hold a revenue-desk
 * request open until the browser gives up — the clerk needs to be told to try
 * again or take the payment another way.
 */
async function providerFetch(
  url: string,
  init: RequestInit & { timeoutMs?: number } = {}
): Promise<{ status: number; body: Record<string, unknown> }> {
  const { timeoutMs = 15_000, ...rest } = init;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(url, { ...rest, signal: controller.signal, cache: 'no-store' });
    const text = await response.text();

    let body: Record<string, unknown> = {};
    try {
      body = text ? (JSON.parse(text) as Record<string, unknown>) : {};
    } catch {
      throw new ProviderError('BAD_RESPONSE', `The provider returned something that is not JSON (HTTP ${response.status}).`, response.status);
    }

    return { status: response.status, body };
  } catch (err) {
    if (err instanceof ProviderError) throw err;
    if ((err as Error)?.name === 'AbortError') {
      throw new ProviderError(
        'TIMEOUT',
        `The payment provider did not respond within ${timeoutMs / 1000} seconds. The payment has NOT been recorded — check the provider's dashboard before retrying.`
      );
    }
    throw new ProviderError('UNREACHABLE', 'The payment provider could not be reached.');
  } finally {
    clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------
// Paystack
// ---------------------------------------------------------------------------
// Amounts in KOBO, which is this application's own unit — so nothing is
// converted here, and nothing should ever be added that does.

const PAYSTACK_BASE = 'https://api.paystack.co';

export class PaystackAdapter implements PaymentProviderAdapter {
  readonly code = 'PAYSTACK' as const;
  readonly supportsNativeSplit = true;

  private get secret(): string {
    return process.env.PAYSTACK_SECRET_KEY ?? '';
  }

  isConfigured(): boolean {
    return this.secret.length > 0;
  }

  private headers(): Record<string, string> {
    if (!this.isConfigured()) {
      throw new ProviderError('NOT_CONFIGURED', 'Paystack is not configured. Set PAYSTACK_SECRET_KEY.');
    }
    return { Authorization: `Bearer ${this.secret}`, 'Content-Type': 'application/json' };
  }

  async initiate(request: InitiateRequest): Promise<InitiateResult> {
    const splitCode = process.env.PAYSTACK_SPLIT_CODE;

    const { status, body } = await providerFetch(`${PAYSTACK_BASE}/transaction/initialize`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({
        reference: request.reference,
        // Already kobo. No conversion.
        amount: request.amount,
        currency: request.currency,
        email: request.email,
        callback_url: request.callbackUrl,
        metadata: request.metadata,
        // §16: where the provider can split at source, let it.
        ...(splitCode ? { split_code: splitCode } : {}),
      }),
    });

    const data = (body.data ?? {}) as Record<string, unknown>;
    if (status !== 200 || body.status !== true || !data.authorization_url) {
      throw new ProviderError('INITIATE_FAILED', String(body.message ?? 'Paystack would not start this transaction.'), status);
    }

    return {
      authorizationUrl: String(data.authorization_url),
      providerReference: String(data.reference ?? request.reference),
      raw: body,
    };
  }

  async verify(reference: string): Promise<VerifyResult> {
    const { status, body } = await providerFetch(
      `${PAYSTACK_BASE}/transaction/verify/${encodeURIComponent(reference)}`,
      { method: 'GET', headers: this.headers() }
    );

    if (status !== 200 || body.status !== true) {
      throw new ProviderError('VERIFY_FAILED', String(body.message ?? 'Paystack could not verify this transaction.'), status);
    }

    const data = (body.data ?? {}) as Record<string, unknown>;
    const amount = data.amount;
    if (typeof amount !== 'number' || !Number.isInteger(amount)) {
      // Refused rather than rounded. A non-integer kobo figure from a gateway is
      // something to investigate, not to coerce into a balance.
      throw new ProviderError('BAD_AMOUNT', `Paystack returned an amount of ${String(amount)}, which is not a whole number of kobo.`);
    }

    return {
      amount,
      currency: String(data.currency ?? 'NGN'),
      status: String(data.status ?? 'unknown'),
      providerTransactionId: data.id != null ? String(data.id) : null,
      paidAt: data.paid_at ? new Date(String(data.paid_at)) : null,
      raw: body,
    };
  }

  verifySignature(params: { rawBody: string; headers: Headers }): SignatureVerdict {
    return verifyPaystackSignature({
      rawBody: params.rawBody,
      signatureHeader: params.headers.get('x-paystack-signature'),
      secretKey: this.secret,
    });
  }

  parseEvent(payload: unknown): NormalisedEvent {
    // Imported lazily through the shared module so both adapters and the route
    // read events the same way.
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { normaliseEvent } = require('./webhooks') as typeof import('./webhooks');
    return normaliseEvent('PAYSTACK', payload);
  }
}

// ---------------------------------------------------------------------------
// Flutterwave
// ---------------------------------------------------------------------------
// Amounts in NAIRA. The conversion to kobo happens here and ONLY here.

const FLUTTERWAVE_BASE = 'https://api.flutterwave.com/v3';

export class FlutterwaveAdapter implements PaymentProviderAdapter {
  readonly code = 'FLUTTERWAVE' as const;
  readonly supportsNativeSplit = true;

  private get secret(): string {
    return process.env.FLUTTERWAVE_SECRET_KEY ?? '';
  }

  isConfigured(): boolean {
    return this.secret.length > 0;
  }

  private headers(): Record<string, string> {
    if (!this.isConfigured()) {
      throw new ProviderError('NOT_CONFIGURED', 'Flutterwave is not configured. Set FLUTTERWAVE_SECRET_KEY.');
    }
    return { Authorization: `Bearer ${this.secret}`, 'Content-Type': 'application/json' };
  }

  async initiate(request: InitiateRequest): Promise<InitiateResult> {
    const { status, body } = await providerFetch(`${FLUTTERWAVE_BASE}/payments`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({
        tx_ref: request.reference,
        // Kobo out to naira. Exact: kobo are integers, and dividing by 100 for
        // transmission cannot lose precision at these magnitudes. The figure
        // that is later BELIEVED comes back through verify() and is converted
        // back with a round, so the round trip is closed.
        amount: request.amount / 100,
        currency: request.currency,
        redirect_url: request.callbackUrl,
        customer: { email: request.email },
        meta: request.metadata,
      }),
    });

    const data = (body.data ?? {}) as Record<string, unknown>;
    if (status >= 400 || body.status !== 'success' || !data.link) {
      throw new ProviderError('INITIATE_FAILED', String(body.message ?? 'Flutterwave would not start this transaction.'), status);
    }

    return { authorizationUrl: String(data.link), providerReference: request.reference, raw: body };
  }

  async verify(reference: string): Promise<VerifyResult> {
    const { status, body } = await providerFetch(
      `${FLUTTERWAVE_BASE}/transactions/verify_by_reference?tx_ref=${encodeURIComponent(reference)}`,
      { method: 'GET', headers: this.headers() }
    );

    if (status >= 400 || body.status !== 'success') {
      throw new ProviderError('VERIFY_FAILED', String(body.message ?? 'Flutterwave could not verify this transaction.'), status);
    }

    const data = (body.data ?? {}) as Record<string, unknown>;
    const major = data.amount;
    if (typeof major !== 'number' || !Number.isFinite(major)) {
      throw new ProviderError('BAD_AMOUNT', `Flutterwave returned an amount of ${String(major)}.`);
    }

    return {
      // Naira to kobo, rounded once, here.
      amount: Math.round(major * 100),
      currency: String(data.currency ?? 'NGN'),
      status: String(data.status ?? 'unknown'),
      providerTransactionId: data.id != null ? String(data.id) : null,
      paidAt: data.created_at ? new Date(String(data.created_at)) : null,
      raw: body,
    };
  }

  verifySignature(params: { rawBody: string; headers: Headers }): SignatureVerdict {
    return verifyFlutterwaveSignature({
      signatureHeader: params.headers.get('verif-hash'),
      webhookHash: process.env.FLUTTERWAVE_WEBHOOK_HASH ?? '',
    });
  }

  parseEvent(payload: unknown): NormalisedEvent {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { normaliseEvent } = require('./webhooks') as typeof import('./webhooks');
    return normaliseEvent('FLUTTERWAVE', payload);
  }
}

// ---------------------------------------------------------------------------
// The registry
// ---------------------------------------------------------------------------

const ADAPTERS: Record<string, PaymentProviderAdapter> = {
  PAYSTACK: new PaystackAdapter(),
  FLUTTERWAVE: new FlutterwaveAdapter(),
};

/**
 * The adapter for a provider code, or null.
 *
 * Returns null rather than throwing for an unknown code, because the commonest
 * caller is a webhook route handling a URL somebody on the internet chose, and
 * an unknown provider there is a 404 rather than a crash.
 */
export function adapterFor(code: string): PaymentProviderAdapter | null {
  return ADAPTERS[code.toUpperCase()] ?? null;
}

/** Which gateways are actually usable right now. For the settings screen. */
export function configuredProviders(): { code: string; configured: boolean; supportsNativeSplit: boolean }[] {
  return Object.values(ADAPTERS).map((a) => ({
    code: a.code,
    configured: a.isConfigured(),
    supportsNativeSplit: a.supportsNativeSplit,
  }));
}
